name: Laravel Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '37 9 1 * *'

jobs:
  laravel-unit-tests:
    name: "Laravel Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extensions: ["scoutapm", ""]
        laravel-version:
          - "5.5.*"
          - "6.*"
          - "7.*"
          - "8.*"
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        exclude:
          - {php-version: "7.1", laravel-version: "6.*"} # Laravel 6 requires 7.2+
          - {php-version: "7.1", laravel-version: "7.*"} # Laravel 7 requires 7.2+
          - {php-version: "7.1", laravel-version: "8.*"} # Laravel 8 requires 7.3+
          - {php-version: "7.2", laravel-version: "8.*"} # Laravel 8 requires 7.3+
    steps:
      - uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl, composer:v2.2
          extensions: ${{ matrix.extensions }}
        env:
          fail-fast: true
      # --no-update then a full `composer update` is needed to overcome locked dependencies
      # See: https://github.com/composer/composer/issues/9561
      - name: "Remove existing requirements components (avoid conflicts)"
        run: "composer remove --dev symfony/* laravel/* --no-update --no-interaction"
      - name: "Require framework ${{ matrix.laravel-version}}"
        run: "composer require laravel/framework:${{ matrix.laravel-version}} --no-update --no-interaction --prefer-dist --prefer-stable"
      - name: "Composer update with new requirements"
        run: "composer update --no-interaction --prefer-dist --prefer-stable"
      - name: "Run PHPUnit (Laravel) test suite"
        run: "vendor/bin/phpunit --testsuite=laravel"

  laravel-e2e:
    name: "Laravel End-to-End Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extensions: ["scoutapm", ""]
        laravel-version:
          - "5.5.*"
          - "6.*"
          - "7.*"
          - "8.*"
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        exclude:
          - {php-version: "7.1", laravel-version: "6.*"} # Laravel 6 requires 7.2+
          - {php-version: "7.1", laravel-version: "7.*"} # Laravel 7 requires 7.2+
          - {php-version: "7.1", laravel-version: "8.*"} # Laravel 8 requires 7.3+
          - {php-version: "7.2", laravel-version: "8.*"} # Laravel 8 requires 7.3+
          - {php-version: "8.0", laravel-version: "5.5.*"} # Laravel 5.5.* does not support PHP 8.0+
    env:
      SCOUT_APM_KEY: ${{ secrets.SCOUT_APM_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: scout-apm-php
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl, composer:v2.2
          extensions: ${{ matrix.extensions }}
        env:
          fail-fast: true
      - name: "Install Laravel quickstart project"
        run: "composer create-project laravel/laravel:${{ matrix.laravel-version}} test-app --prefer-dist"
      - name: "Add scout-apm-php as a repository"
        run: cd test-app && composer config repositories.scout path ../scout-apm-php
      - name: "Require scout-apm-php current checkout"
        run: cd test-app && composer require scoutapp/scout-apm-php:*@dev composer/package-versions-deprecated
      - name: "Publish the provider"
        run: cd test-app && php artisan vendor:publish --provider="Scoutapm\Laravel\Providers\ScoutApmServiceProvider"
      - name: "Configure Scout"
        run: cd test-app && echo -e "\nSCOUT_KEY=\"\${SCOUT_APM_KEY}\"\nSCOUT_NAME=\"My Laravel App\"\nSCOUT_MONITOR=true\nSCOUT_LOG_LEVEL=\"debug\"" >> .env
      - name: "Load the index page to trigger instrumentation"
        run: |
          cd test-app
          cat .env
          php artisan serve &
          # Give Laravel a chance to start...
          sleep 2
          # Very occasionally in GH Actions, core-agent didn't quite start in time - so load the page twice
          wget -O /dev/null http://localhost:8000
          sleep 1
          wget http://localhost:8000
          cat index.html
          ps -ax
      - name: "Check logs for successful payload send"
        run: |
          cd test-app
          cat storage/logs/laravel.log
          grep -q "local.DEBUG: \[Scout\] Sent whole payload successfully to core agent." storage/logs/laravel.log
